const std = @import("std");

pub const Index = u32;

pub const Token = struct {
    tag: Token.Tag,
    start: u32,
    end: u32,

    pub const Index = u32;

    pub const Tag = enum(u8) {
        invalid,
        eof,
        identifier,
        integer_literal,
        float_literal,
        string_literal,

        // Keywords.
        keyword_if,
        keyword_else,
        keyword_then,
        keyword_ifx,
        keyword_for,
        keyword_while,
        keyword_return,
        keyword_break,
        keyword_continue,
        keyword_defer,
        keyword_using,
        keyword_struct,
        keyword_union,
        keyword_enum,
        keyword_enum_flags,
        keyword_cast,
        keyword_xx,
        keyword_inline,
        keyword_no_inline,
        keyword_null,
        keyword_true,
        keyword_false,
        keyword_void,
        keyword_it,
        keyword_it_index,
        keyword_push_context,
        keyword_operator,
        keyword_case,
        keyword_size_of,
        keyword_type_of,
        keyword_type_info,
        keyword_is_constant,
        keyword_interface,

        // Directives.
        directive_run,
        directive_if,
        directive_ifx,
        directive_else,
        directive_import,
        directive_load,
        directive_insert,
        directive_code,
        directive_expand,
        directive_char,
        directive_string,
        directive_foreign,
        directive_foreign_library,
        directive_system_library,
        directive_library,
        directive_type,
        directive_scope_file,
        directive_scope_export,
        directive_scope_module,
        directive_as,
        directive_place,
        directive_align,
        directive_no_padding,
        directive_specified,
        directive_through,
        directive_complete,
        directive_must,
        directive_this,
        directive_procedure_name,
        directive_deprecated,
        directive_assert,
        directive_dump,
        directive_symmetric,
        directive_poke_name,
        directive_compile_time,
        directive_no_reset,
        directive_no_abc,
        directive_no_context,
        directive_c_call,
        directive_add_context,
        directive_asm,
        directive_bytes,
        directive_intrinsic,
        directive_program_export,
        directive_cpp_method,
        directive_elsewhere,
        directive_runtime_support,
        directive_bake_arguments,
        directive_bake_constants,
        directive_modify,
        directive_module_parameters,
        directive_type_info_none,
        directive_type_info_procedures_are_void_pointers,
        directive_placeholder,
        directive_compiler,
        directive_file,
        directive_line,
        directive_filepath,
        directive_location,
        directive_caller_location,
        directive_caller_code,
        directive_procedure_of_call,

        colon_colon,
        colon_equal,
        colon,
        equal,
        equal_equal,
        bang_equal,
        less_than,
        less_equal,
        greater_than,
        greater_equal,
        plus,
        minus,
        star,
        slash,
        percent,
        ampersand,
        pipe,
        caret,
        tilde,
        shift_left,
        shift_right,
        shift_left_rotate,
        shift_right_rotate,
        ampersand_ampersand,
        pipe_pipe,
        pipe_pipe_equal,
        bang,
        plus_equal,
        minus_equal,
        star_equal,
        slash_equal,
        ampersand_equal,
        pipe_equal,
        caret_equal,
        dot_dot,
        dot,
        comma,
        semicolon,
        l_paren,
        r_paren,
        l_brace,
        r_brace,
        l_bracket,
        r_bracket,
        arrow,
        fat_arrow,
        dollar,
        dollar_dollar,
        at,
        triple_minus,
        dot_star,
    };
};

pub const Tag = Token.Tag;

pub fn keywordOrIdentifier(bytes: []const u8) Tag {
    const keywords = std.StaticStringMap(Tag).initComptime(.{
        .{ "if", .keyword_if }, .{ "else", .keyword_else }, .{ "then", .keyword_then },
        .{ "ifx", .keyword_ifx }, .{ "for", .keyword_for }, .{ "while", .keyword_while },
        .{ "return", .keyword_return }, .{ "break", .keyword_break }, .{ "continue", .keyword_continue },
        .{ "defer", .keyword_defer }, .{ "using", .keyword_using }, .{ "struct", .keyword_struct },
        .{ "union", .keyword_union }, .{ "enum", .keyword_enum }, .{ "enum_flags", .keyword_enum_flags },
        .{ "cast", .keyword_cast }, .{ "xx", .keyword_xx }, .{ "inline", .keyword_inline },
        .{ "no_inline", .keyword_no_inline }, .{ "null", .keyword_null }, .{ "true", .keyword_true },
        .{ "false", .keyword_false }, .{ "void", .keyword_void }, .{ "it", .keyword_it },
        .{ "it_index", .keyword_it_index }, .{ "push_context", .keyword_push_context },
        .{ "operator", .keyword_operator }, .{ "case", .keyword_case }, .{ "size_of", .keyword_size_of },
        .{ "type_of", .keyword_type_of }, .{ "type_info", .keyword_type_info },
        .{ "is_constant", .keyword_is_constant }, .{ "interface", .keyword_interface },
    });
    return keywords.get(bytes) orelse .identifier;
}

pub fn directiveOrInvalid(bytes: []const u8) Tag {
    const directives = std.StaticStringMap(Tag).initComptime(.{
        .{ "#run", .directive_run }, .{ "#if", .directive_if }, .{ "#ifx", .directive_ifx },
        .{ "#else", .directive_else }, .{ "#import", .directive_import }, .{ "#load", .directive_load },
        .{ "#insert", .directive_insert }, .{ "#code", .directive_code }, .{ "#expand", .directive_expand },
        .{ "#char", .directive_char }, .{ "#string", .directive_string }, .{ "#foreign", .directive_foreign },
        .{ "#foreign_library", .directive_foreign_library },
        .{ "#foreign_system_library", .directive_system_library },
        .{ "#system_library", .directive_system_library }, .{ "#library", .directive_library },
        .{ "#type", .directive_type }, .{ "#scope_file", .directive_scope_file },
        .{ "#scope_export", .directive_scope_export }, .{ "#scope_module", .directive_scope_module },
        .{ "#as", .directive_as }, .{ "#place", .directive_place }, .{ "#align", .directive_align },
        .{ "#no_padding", .directive_no_padding }, .{ "#specified", .directive_specified },
        .{ "#through", .directive_through }, .{ "#complete", .directive_complete }, .{ "#must", .directive_must },
        .{ "#this", .directive_this }, .{ "#procedure_name", .directive_procedure_name },
        .{ "#deprecated", .directive_deprecated }, .{ "#assert", .directive_assert }, .{ "#dump", .directive_dump },
        .{ "#symmetric", .directive_symmetric }, .{ "#poke_name", .directive_poke_name },
        .{ "#compile_time", .directive_compile_time }, .{ "#no_reset", .directive_no_reset },
        .{ "#no_abc", .directive_no_abc }, .{ "#no_context", .directive_no_context },
        .{ "#c_call", .directive_c_call }, .{ "#add_context", .directive_add_context }, .{ "#asm", .directive_asm },
        .{ "#bytes", .directive_bytes }, .{ "#intrinsic", .directive_intrinsic },
        .{ "#program_export", .directive_program_export }, .{ "#cpp_method", .directive_cpp_method }, .{ "#elsewhere", .directive_elsewhere },
        .{ "#runtime_support", .directive_runtime_support }, .{ "#bake_arguments", .directive_bake_arguments },
        .{ "#bake_constants", .directive_bake_constants }, .{ "#modify", .directive_modify },
        .{ "#module_parameters", .directive_module_parameters }, .{ "#type_info_none", .directive_type_info_none },
        .{ "#type_info_procedures_are_void_pointers", .directive_type_info_procedures_are_void_pointers },
        .{ "#placeholder", .directive_placeholder }, .{ "#compiler", .directive_compiler },
        .{ "#file", .directive_file }, .{ "#line", .directive_line }, .{ "#filepath", .directive_filepath },
        .{ "#location", .directive_location }, .{ "#caller_location", .directive_caller_location },
        .{ "#caller_code", .directive_caller_code }, .{ "#procedure_of_call", .directive_procedure_of_call },
    });
    return directives.get(bytes) orelse .invalid;
}

pub fn directiveNameOrInvalid(bytes: []const u8) Tag {
    var buf: [128]u8 = undefined;
    if (bytes.len + 1 > buf.len) return .invalid;
    buf[0] = '#';
    @memcpy(buf[1 .. bytes.len + 1], bytes);
    return directiveOrInvalid(buf[0 .. bytes.len + 1]);
}
